version: '3.8'
services:
  task-hive-back:
    container_name: task-hive-back
    build: .
    ports:
      - "3333:3333"
    env_file:
      - .env
    restart: always
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: task-hive-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - task-hive-back
    networks:
      - app_network

networks:
  app_network:
    driver: bridge