
export enum PostgreSQLTokens {
  DATA_SOURCE = 'DATA_POSTGRESQL',

  COMPANY_REPOSITORY = 'COMPANY_REPOSITORY',
  PROJECT_REPOSITORY = 'PROJECT_REPOSITORY',
  PROJECT_STAGE_REPOSITORY = 'PROJECT_STAGE_REPOSITORY',
  TASK_REPOSITORY = 'TASK_REPOSITORY',
  TASK_TIMETRACK_REPOSITORY = 'TASK_TIMETRACK_REPOSITORY',
  TODO_REPOSITORY = 'TODO_REPOSITORY',
  TODO_COMPLETED_REPOSITORY = 'TODO_COMPLETED_REPOSITORY',
  TODO_TYPE_REPOSITORY = 'TODO_TYPE_REPOSITORY',
  USER_REPOSITORY = 'USER_REPOSITORY',
  USER_FRIENDSHIP_REPOSITORY = 'USER_FRIENDSHIP_REPOSITORY',
  SESSION_REPOSITORY = 'SESSION_REPOSITORY',
  FORGET_PASSWORD = 'FORGET_PASSWORD',
}

export enum ToDoStatus {
  TODO = 'TODO',
  DONE = 'DONE',
  CANCELLED = 'CANCELLED',
  PAUSED = 'PAUSED',
  CREATED = 'CREATED',
}

export enum ToDoTypes {
  PUNCTUAL = 'PUNCTUAL',
  RECURRING = 'RECURRING',
}

export enum RecurringTypes {
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
  MONTHLY = 'MONTHLY',
}